upstream backends {
    server api-server-1:5252;
    server api-server-2:5252;
}

server {
    listen 80;

    location / {
        proxy_pass http://front-end-server:9000;
    }

    location /api {
        proxy_pass http://backends/api;
    }
}